# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identification.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14identification.proto\"+\n\x15IdentificationRequest\x12\x12\n\nvideo_path\x18\x01 \x01(\t\")\n\x16IdentificationResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t2T\n\x15IdentificationService\x12;\n\x08Identify\x12\x16.IdentificationRequest\x1a\x17.IdentificationResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'identification_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IDENTIFICATIONREQUEST._serialized_start=24
  _IDENTIFICATIONREQUEST._serialized_end=67
  _IDENTIFICATIONRESPONSE._serialized_start=69
  _IDENTIFICATIONRESPONSE._serialized_end=110
  _IDENTIFICATIONSERVICE._serialized_start=112
  _IDENTIFICATIONSERVICE._serialized_end=196
# @@protoc_insertion_point(module_scope)
