# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import app_services.identification_pb2 as identification__pb2


class IdentificationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Identify = channel.unary_unary(
                '/IdentificationService/Identify',
                request_serializer=identification__pb2.IdentificationRequest.SerializeToString,
                response_deserializer=identification__pb2.IdentificationResponse.FromString,
                )


class IdentificationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Identify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IdentificationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Identify': grpc.unary_unary_rpc_method_handler(
                    servicer.Identify,
                    request_deserializer=identification__pb2.IdentificationRequest.FromString,
                    response_serializer=identification__pb2.IdentificationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'IdentificationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IdentificationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Identify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/IdentificationService/Identify',
            identification__pb2.IdentificationRequest.SerializeToString,
            identification__pb2.IdentificationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
