# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: verification.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12verification.proto\":\n\x13VerificationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nvideo_path\x18\x02 \x01(\t\"<\n\x14VerificationResponse\x12\x10\n\x08verified\x18\x01 \x01(\x08\x12\x12\n\nsimilarity\x18\x02 \x01(\x02\x32L\n\x13VerificationService\x12\x35\n\x06Verify\x12\x14.VerificationRequest\x1a\x15.VerificationResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'verification_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VERIFICATIONREQUEST._serialized_start=22
  _VERIFICATIONREQUEST._serialized_end=80
  _VERIFICATIONRESPONSE._serialized_start=82
  _VERIFICATIONRESPONSE._serialized_end=142
  _VERIFICATIONSERVICE._serialized_start=144
  _VERIFICATIONSERVICE._serialized_end=220
# @@protoc_insertion_point(module_scope)
